[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-agent-definition",
    "allow-get-agent-definitions",
    "allow-get-agent-streams",
    "allow-get-agent-spec",
    "allow-new-agent-stream",
    "allow-rename-agent-stream",
    "allow-unique-stream-name",
    "allow-add-agent-stream",
    "allow-remove-agent-stream",
    "allow-insert-agent-stream",
    "allow-copy-sub-stream",
    "allow-start-agent-stream",
    "allow-stop-agent-stream",
    "allow-new-agent-stream-node",
    "allow-add-agent-stream-node",
    "allow-remove-agent-stream-node",
    "allow-add-agent-stream-edge",
    "allow-remove-agent-stream-edge",
    "allow-start-agent",
    "allow-stop-agent",
    "allow-write-board",
    "allow-set-agent-configs",
    "allow-get-global-configs",
    "allow-get-global-configs-map",
    "allow-set-global-configs",
    "allow-set-global-configs-map",
    "allow-get-agent-config-specs",
]
